### ISSUE TITLE
Display Muting rule details to incident details

### ISSUE THREAD

**Issue by SNGoutham** [newrelic-experimental/nr1-command-center-v2#5]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

## Summary
Include muting rule details to the open incidents. This would help DevOps or SRE Engineers to view any on going issues which are muted during change windows.

[NOTE]: # ( Provide a brief overview of what the new feature is all about. )

## Desired Behavior

1. In the overview section, Display number of muted issues as an additional item for each account.
2. In the Open incidents tab, display muting rule id and muting rule name, if an incident is muted.

[NOTE]: # ( Tell us how the new feature should work. Be specific. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Possible Solution

[NOTE]: # ( Not required. Suggest how to implement the addition or change. )

## Additional context

[TIP]:  # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by khpeet** [comment]
@SNGoutham - resolved in commit: https://github.com/newrelic-experimental/nr1-command-center-v2/commit/dbf733ce61e712afc5e91393bce6c681a2d0938f
